### ISSUE TITLE
Console error: foundry.js:319 TypeError: Cannot read properties of null (reading 'data')

### ISSUE THREAD

**Issue by yjeroen** [zeel01/pin-fixer#17]
When loading the world:

![image](https://user-images.githubusercontent.com/1303988/162629365-6b3287bc-79d8-41d6-b311-bc97b4b2d323.png)

**Comment by zeel01** [comment]
I'll need a bit more information. What version of Foundry are you using? What game system, and system version? What version of Pin Fixer? Do you see this issue when Pin Fixer is the *only* module enabled?

**Comment by yjeroen** [comment]
Foundry v9 255
Forbidden Lands system 9.255

However, I can't reproduce it any more. I'll close this untill I see it again.
