### ISSUE TITLE
Feature Suggestion: Allow Notes to be on top of Fog layer for a given scene.

### ISSUE THREAD

**Issue by akrigline** [zeel01/pin-fixer#4]
This is super useful for `image-fog` use case:
Setting `canvas.notes.zIndex = 300` will pull the notes layer above all currently known fog layers.

Example:
![image](https://user-images.githubusercontent.com/7644614/100412946-0da8ae80-3044-11eb-85d5-9c9926c0dc36.png)

[Duplicates Image Fog issue #16](https://github.com/ElfFriend-DnD/foundryvtt-imageFog/issues/16)

**Comment by zeel01** [comment]
Feature implemented, should work!
